name: AudioRec

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
        
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x

      - run: |
          dotnet restore
          dotnet build
          dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true /p:SelfContained=true
                    
      - run: |
          Compress-Archive -Path bin/Release/net9.0/win-x64/publish/* -DestinationPath AudioRec.zip

      - uses: softprops/action-gh-release@v1
        with:
          files: AudioRec.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

